-- SELECT *   -- 필드1, 필드2,...
--     FORM TEST;  -- 테이블명


SELECT SYSDATE
FROM DUAL;
-- 가상테이블 제공하고 있음

-- 테이블 생성 방법법
/*
    CREATE TABLE 테이블이름(
        컬럼명 DATATYPE [ NULL | NOT NULL ] [ CONSTRAINT 별칭 제약조건 ] ,
        컬럼명 DATATYPE [ NULL | NOT NULL ] [ CONSTRAINT 별칭 제약조건 ] ,
        .....
    );
*/

-- 제약조건 ---------------------
-- 제약조건명 ==>  테이블명_필드명_성격(PK, FK, CK, UN,....)
CREATE TABLE USERLIST
(
    ID   VARCHAR2(10) CONSTRAINT ID_PK PRIMARY KEY,
    NAME VARCHAR2(10) --NOT NULL
);

DROP TABLE USERLIST;
SELECT *
FROM USERLIST;
INSERT INTO USERLIST
VALUES ('KINGSMILE', 'AA');
INSERT INTO USERLIST
VALUES ('YUNA2', '김연아');
INSERT INTO USERLIST(ID)
VALUES ('CCC');

DELETE
FROM USERLIST; -- DELETE : 레코드 삭제
ROLLBACK;
/*
CREATE TABLE FK_MEMBER(
    CODE NUMBER(2) NOT NULL ,
    ID VARCHAR2(20) NOT NULL
    CONSTRAINT ID_FK REFERENCES MEMBER(ID) ,
    ETC VARCHAR2(10)
);
*/

CREATE TABLE USERLIST_UN
(
    ID    VARCHAR2(10) CONSTRAINT USERLIST_UN_ID_PK PRIMARY KEY, -- 기본키 유일성, 널허용하지 않음, 중복허용안함
    JUMIN CHAR(13)
        CONSTRAINT JUMIN_UN UNIQUE                               -- 유니크 유일성, 중복허용않음, 널허용
);

SELECT *
FROM USERLIST_UN;
INSERT INTO USERLIST_UN
VALUES ('AA', '111');
INSERT INTO USERLIST_UN
VALUES ('BB', '222');
INSERT INTO USERLIST_UN
VALUES ('CC', '33');

INSERT INTO USERLIST_UN(ID)
VALUES ('BB'); -- PK 위배
INSERT INTO USERLIST_UN(ID)
VALUES ('PPP'); -- UNIQUE 위배안됨


CREATE TABLE CK_TEST
(
    NAME VARCHAR2(10) NOT NULL,
    AGE  NUMBER(2) NOT NULL
        CHECK (AGE BETWEEN 20 AND 30 )
    --AGE컬럼의 값은 20~30사이만 허용
);

SELECT *
FROM CK_TEST;

INSERT INTO CK_TEST
VALUES ('AA', 22);
INSERT INTO CK_TEST
VALUES ('AA', 30);
INSERT INTO CK_TEST
VALUES ('AA', 55);
INSERT INTO CK_TEST
VALUES ('AA', 12);
INSERT INTO CK_TEST
VALUES ('AA', 44);

CREATE TABLE DE_TEST
(
    NAME VARCHAR2(10) NOT NULL,
    ADDR VARCHAR2(10) DEFAULT '서울'
);

SELECT *
FROM DE_TEST;

INSERT INTO DE_TEST
VALUES ('AA', 'JEJU');
INSERT INTO DE_TEST
VALUES ('BB', 'SEOUL');
INSERT INTO DE_TEST
VALUES ('CC', '서울');
INSERT INTO DE_TEST
VALUES ('DD', '부산');

INSERT INTO DE_TEST
VALUES ('PP', DEFAULT);

INSERT INTO DE_TEST
VALUES ('KK', NULL);

INSERT INTO DE_TEST(NAME)
VALUES ('BB'); --
INSERT INTO DE_TEST(NAME)
VALUES ('CC');
INSERT INTO DE_TEST(NAME)
VALUES ('DD');
