CREATE TABLE SPRING_BOARD
(
    NUM     NUMBER,
    NAME    VARCHAR2(50),
    EMAIL   VARCHAR2(50),
    PWD     VARCHAR2(50),
    SUBJECT VARCHAR2(50),
    CONTENT VARCHAR2(2000),
    REGDATE DATE,
    HIT     NUMBER DEFAULT 0,
    PARENT  NUMBER,
    SORT    NUMBER DEFAULT 0,
    TAB     NUMBER DEFAULT 0
);

SELECT NVL(MAX(NUM), 0) + 1
FROM SPRING_BOARD;

SELECT *
FROM (SELECT A.*, ROWNUM RNUM FROM (SELECT * FROM SPRING_BOARD ORDER BY PARENT DESC, SORT ASC) A)
WHERE RNUM BETWEEN 1 AND 10;