SELECT *
FROM MYBATISBOARD;

CREATE TABLE MYBATISBOARD
(
    SEQ       INT NOT NULL AUTO_INCREMENT,
    TITLE     VARCHAR2(50),
    WRITER    VARCHAR2(30),
    CONTENT   VARCHAR2(200),
    REGDATE   DATE,
    READCOUNT INT
);

CREATE TABLE `MYBATISBOARD`
(
    SEQ       INT         NOT NULL AUTO_INCREMENT,
    TITLE     VARCHAR(50) NOT NULL DEFAULT 'title',
    WRITER    VARCHAR(30) NOT NULL DEFAULT 'writer',
    CONTENT   TEXT(2000) NOT NULL DEFAULT 'contents',
    REGDATE   DATE        NOT NULL DEFAULT CURDATE(),
    READCOUNT INT NULL DEFAULT '0'
) COLLATE='utf8_general_ci'
;

CREATE SEQUENCE BOARD_SEQ;

INSERT INTO MYBATISBOARD(TITLE, WRITER, CONTENT, REGDATE, READCOUNT)
VALUES ('title', 'writer', 'contents', CURDATE(), 0);


----------------------------------------------------------------------
SELECT *
FROM MYBATISBOARD;

CREATE TABLE MYBATISBOARD
(
    SEQ       NUMBER,
    TITLE     VARCHAR2(50),
    WRITER    VARCHAR2(30),
    CONTENT   VARCHAR2(200),
    REGDATE   DATE,
    READCOUNT NUMBER
);

CREATE SEQUENCE BOARD_SEQ;

INSERT INTO MYBATISBOARD
VALUES (BOARD_SEQ.NEXTVAL, 'title', 'writer', 'contents', sysdate, 0);